### ISSUE TITLE
Switch to pure CSS for the badges

### ISSUE THREAD

**Issue by XhmikosR** [ScottHelme/securityheaders-bugs#2]
Just for fun, for `.score_green`:

```css
.score_green {
    background-color: #2B9100;
    border-radius: 12px;
    border: 2px solid #257900;
}

.score_green,
.score_grey,
.score_lightgreen,
.score_orange,
.score_red,
.score_yellow {
    line-height: 130px;  /* needed to properly vertically-align since `height` is 130px */
}
```

And so on.

Keep up the good work!
